name: Build Waypoint Plugin

on:
  push:
    tags-ignore:
      - '**' # ignore all
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Plugin
      run: make build-docker
